---
language: python
python: "2.7"
install:
  - pip install -r requirements.txt
script:
  - echo localhost > inventory
  - ansible-playbook --syntax-check -i inventory role.yml
  - ansible-playbook -i inventory role.yml --connection=local -vvvv
